name: check

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/check.yml"
      - "assets/**"
      - "tools/schema/**"
  pull_request:
    branches:
      - "**"
    paths:
      - ".github/workflows/check.yml"
      - "assets/**"
      - "tools/schema/**"
  workflow_dispatch:

jobs:
  resource:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Run maa-checker
        run: |
          pnpm i
          pnpm run check

      - name: Validate JSON Schema
        run: |
          python -m pip install jsonschema==4.26.0 referencing==0.37.0
          python tools/validate_schema.py --resource-dirs assets/resource_fast assets/resource assets/resource_bilibili ./assets/resource_en --exclude-dirs assets/resource/gamedata assets/resource/image --task-dirs assets/tasks
